name: E2E Tests with Cypress

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Iniciar servidor de desarrollo
        run: npm run dev &
        env:
          NODE_ENV: development

      - name: Esperar que el servidor esté listo
        uses: jakejarvis/wait-action@master
        with:
          url: 'http://localhost:5173'
          timeout: 60

      - name: Ejecutar tests de Cypress
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 60
