name: E2E Tests with Cypress

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Instalar dependencias
        run: npm install

      - name: Build app
        run: npm run build

      - name: Artifac upload
        uses: actions/upload-artifact@v3
        with:
          name: ContadorVue
          path: ContadorVue
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deply to Github
        id: deployment
        uses: actions/deploy-pages@v4