name: E2E Tests with Cypress

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ContadorVue

    steps:
      - name: Clonar el repo
        uses: actions/checkout@v3

      - name: Usar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests de Cypress
        uses: cypress-io/github-action@v6
        with:
          working-directory: ContadorVue
          start: npm run dev
          wait-on: 'http://localhost:5173'
          wait-on-timeout: 60
